LOAD DATA INFILE 'monstername.csv'
INTO TABLE `monstername`
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
ENCLOSED BY '\"'
LINES TERMINATED BY '\r\n'

LOAD DATA INFILE 'attributename.csv'
INTO TABLE `attributename`
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
ENCLOSED BY '\"'
LINES TERMINATED BY '\r\n'

LOAD DATA INFILE 'monster.csv'
INTO TABLE `monster`
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
ENCLOSED BY '\"'
LINES TERMINATED BY '\r\n'

LOAD DATA INFILE 'monsterattributes.csv'
INTO TABLE `monsterattributes`
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
ENCLOSED BY '\"'
LINES TERMINATED BY '\r\n'